/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.18
 * Generated at: 2026-03-25 13:44:47 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import ma.ac.esi.gameverseacademy.model.Mod;

public final class editMod_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("ma.ac.esi.gameverseacademy.model.Mod");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
 Mod mod = (Mod) request.getAttribute("mod"); 
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("<title>Edit Mod — GameVerse Academy</title>\r\n");
      out.write("<link href=\"https://fonts.googleapis.com/css2?family=Rajdhani:wght@400;500;600;700&family=Orbitron:wght@400;600;700;900&family=Inter:wght@300;400;500&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("<style>\r\n");
      out.write(":root {\r\n");
      out.write("    --bg: #07050f; --panel: #110e22; --panel2: #1a1530;\r\n");
      out.write("    --purple: #8b5cf6; --purple-bright: #a78bfa;\r\n");
      out.write("    --pink: #ec4899; --pink-bright: #f472b6;\r\n");
      out.write("    --blue: #3b82f6; --blue-bright: #60a5fa;\r\n");
      out.write("    --white: #f0eaff; --dim: #7c6fa0;\r\n");
      out.write("    --border: rgba(139,92,246,0.18); --border-focus: rgba(139,92,246,0.55);\r\n");
      out.write("}\r\n");
      out.write("* { box-sizing: border-box; margin: 0; padding: 0; }\r\n");
      out.write("body {\r\n");
      out.write("    background: var(--bg); color: var(--white);\r\n");
      out.write("    font-family: 'Inter', sans-serif; min-height: 100vh;\r\n");
      out.write("    display: flex; align-items: center; justify-content: center; padding: 40px 20px;\r\n");
      out.write("    position: relative; overflow-x: hidden;\r\n");
      out.write("}\r\n");
      out.write(".blob { position: fixed; border-radius: 50%; filter: blur(120px); pointer-events: none; z-index: 0; opacity: 0.1; }\r\n");
      out.write(".blob-1 { width: 500px; height: 500px; background: var(--purple); top: -150px; left: -100px; }\r\n");
      out.write(".blob-2 { width: 400px; height: 400px; background: var(--pink); bottom: -120px; right: -80px; }\r\n");
      out.write("\r\n");
      out.write(".card {\r\n");
      out.write("    background: rgba(17,14,34,0.9); border: 1px solid var(--border);\r\n");
      out.write("    border-radius: 24px; padding: 44px 40px; width: 100%; max-width: 520px;\r\n");
      out.write("    position: relative; z-index: 1;\r\n");
      out.write("    backdrop-filter: blur(20px);\r\n");
      out.write("    box-shadow: 0 30px 80px rgba(0,0,0,0.5), 0 0 0 1px rgba(139,92,246,0.08);\r\n");
      out.write("    animation: slideUp 0.5s ease;\r\n");
      out.write("}\r\n");
      out.write(".card::before {\r\n");
      out.write("    content: ''; position: absolute; top: 0; left: 30px; right: 30px; height: 2px;\r\n");
      out.write("    background: linear-gradient(90deg, transparent, var(--purple), var(--pink), transparent);\r\n");
      out.write("    border-radius: 0 0 2px 2px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".header { text-align: center; margin-bottom: 36px; }\r\n");
      out.write(".header-icon { font-size: 2.5rem; margin-bottom: 12px; }\r\n");
      out.write(".header h1 {\r\n");
      out.write("    font-family: 'Orbitron', sans-serif; font-size: 1.3rem; font-weight: 700;\r\n");
      out.write("    background: linear-gradient(135deg, var(--purple-bright), var(--pink-bright));\r\n");
      out.write("    -webkit-background-clip: text; -webkit-text-fill-color: transparent; background-clip: text;\r\n");
      out.write("    margin-bottom: 6px;\r\n");
      out.write("}\r\n");
      out.write(".header p { font-size: 0.8rem; color: var(--dim); }\r\n");
      out.write("\r\n");
      out.write(".field-group { margin-bottom: 20px; }\r\n");
      out.write("label {\r\n");
      out.write("    display: block; font-family: 'Rajdhani', sans-serif; font-size: 0.8rem;\r\n");
      out.write("    font-weight: 700; text-transform: uppercase; letter-spacing: 1.5px;\r\n");
      out.write("    color: var(--dim); margin-bottom: 8px;\r\n");
      out.write("}\r\n");
      out.write("input[type=\"text\"], textarea {\r\n");
      out.write("    width: 100%; padding: 13px 16px;\r\n");
      out.write("    background: rgba(26,21,48,0.8); border: 1px solid var(--border);\r\n");
      out.write("    border-radius: 10px; color: var(--white);\r\n");
      out.write("    font-family: 'Inter', sans-serif; font-size: 0.9rem;\r\n");
      out.write("    outline: none; transition: all 0.3s; resize: none;\r\n");
      out.write("}\r\n");
      out.write("input[type=\"text\"]:focus, textarea:focus {\r\n");
      out.write("    border-color: var(--purple);\r\n");
      out.write("    box-shadow: 0 0 0 3px rgba(139,92,246,0.15), 0 0 20px rgba(139,92,246,0.1);\r\n");
      out.write("    background: rgba(139,92,246,0.05);\r\n");
      out.write("}\r\n");
      out.write("input[type=\"text\"]::placeholder, textarea::placeholder { color: var(--dim); }\r\n");
      out.write("textarea { height: 110px; }\r\n");
      out.write("\r\n");
      out.write(".btn-row { display: flex; gap: 12px; margin-top: 30px; }\r\n");
      out.write(".btn-update {\r\n");
      out.write("    flex: 1; padding: 14px; border-radius: 12px;\r\n");
      out.write("    background: linear-gradient(135deg, var(--purple), var(--pink));\r\n");
      out.write("    color: white; border: none; font-family: 'Orbitron', sans-serif;\r\n");
      out.write("    font-size: 0.8rem; font-weight: 700; letter-spacing: 1px; cursor: pointer;\r\n");
      out.write("    transition: all 0.3s; box-shadow: 0 4px 20px rgba(139,92,246,0.4);\r\n");
      out.write("}\r\n");
      out.write(".btn-update:hover { transform: translateY(-2px); box-shadow: 0 8px 30px rgba(139,92,246,0.6); }\r\n");
      out.write(".btn-cancel {\r\n");
      out.write("    padding: 14px 20px; border-radius: 12px;\r\n");
      out.write("    background: transparent; border: 1px solid var(--border);\r\n");
      out.write("    color: var(--dim); font-family: 'Rajdhani', sans-serif;\r\n");
      out.write("    font-size: 0.9rem; font-weight: 700; cursor: pointer;\r\n");
      out.write("    text-decoration: none; display: flex; align-items: center;\r\n");
      out.write("    transition: all 0.25s;\r\n");
      out.write("}\r\n");
      out.write(".btn-cancel:hover { border-color: var(--purple); color: var(--purple-bright); }\r\n");
      out.write("\r\n");
      out.write("@keyframes slideUp { from { opacity: 0; transform: translateY(30px); } to { opacity: 1; transform: translateY(0); } }\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<div class=\"blob blob-1\"></div>\r\n");
      out.write("<div class=\"blob blob-2\"></div>\r\n");
      out.write("\r\n");
      out.write("<div class=\"card\">\r\n");
      out.write("    <div class=\"header\">\r\n");
      out.write("        <div class=\"header-icon\">✏️</div>\r\n");
      out.write("        <h1>Edit Mod</h1>\r\n");
      out.write("        <p>Update your mod details below</p>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <form action=\"");
      out.print( request.getContextPath() );
      out.write("/ModEditController\" method=\"post\">\r\n");
      out.write("        <input type=\"hidden\" name=\"id\" value=\"");
      out.print( mod.getId() );
      out.write("\">\r\n");
      out.write("\r\n");
      out.write("        <div class=\"field-group\">\r\n");
      out.write("            <label>Title</label>\r\n");
      out.write("            <input type=\"text\" name=\"title\" value=\"");
      out.print( mod.getTitle() );
      out.write("\" placeholder=\"Mod title\" required>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"field-group\">\r\n");
      out.write("            <label>Category</label>\r\n");
      out.write("            <input type=\"text\" name=\"category\" value=\"");
      out.print( mod.getCategory() );
      out.write("\" placeholder=\"e.g. Graphique, Gameplay\">\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"field-group\">\r\n");
      out.write("            <label>Author</label>\r\n");
      out.write("            <input type=\"text\" name=\"author\" value=\"");
      out.print( mod.getAuthor() );
      out.write("\" placeholder=\"Your name or username\">\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"field-group\">\r\n");
      out.write("            <label>Description</label>\r\n");
      out.write("            <textarea name=\"description\" placeholder=\"Describe your mod...\">");
      out.print( mod.getDescription() );
      out.write("</textarea>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"btn-row\">\r\n");
      out.write("            <a href=\"");
      out.print( request.getContextPath() );
      out.write("/mods\" class=\"btn-cancel\">← Cancel</a>\r\n");
      out.write("            <button type=\"submit\" class=\"btn-update\">⚡ Update Mod</button>\r\n");
      out.write("        </div>\r\n");
      out.write("    </form>\r\n");
      out.write("</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
