/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.18
 * Generated at: 2026-04-22 23:31:20 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import java.util.*;
import ma.ac.esi.gameverseacademy.model.Mod;

public final class mods_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("ma.ac.esi.gameverseacademy.model.Mod");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

    List<Mod> mods = (List<Mod>) request.getAttribute("mods");
    String currentCategory = (String) request.getAttribute("category");
    String userLogin = (String) session.getAttribute("login");
    HashMap<String, String> gameImages = new HashMap<>();
    gameImages.put("skyrim", "https://media.rawg.io/media/games/7cf/7cfc9220b401b7a300e409e539c9afd5.jpg");
    gameImages.put("gta", "https://media.rawg.io/media/games/456/456dea5e1c7e3cd07060c14e96612001.jpg");
    gameImages.put("witcher", "https://media.rawg.io/media/games/618/618c2031a07bbff6b4f611f10b6bcdbc.jpg");
    String fallbackImg = "https://media.rawg.io/media/screenshots/0e3/0e3f885f8f87143e33f3805ec6c2dfc9.jpg";

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("<title>GameVerse Academy — Mods Hub</title>\r\n");
      out.write("<link href=\"https://fonts.googleapis.com/css2?family=Rajdhani:wght@400;500;600;700&family=Orbitron:wght@400;600;700;900&family=Inter:wght@300;400;500&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("<style>\r\n");
      out.write(":root {\r\n");
      out.write("    --sidebar-w: 270px;\r\n");
      out.write("    --bg: #07050f; --bg2: #0d0a1a; --panel: #110e22; --panel2: #1a1530;\r\n");
      out.write("    --purple: #8b5cf6; --purple-bright: #a78bfa;\r\n");
      out.write("    --pink: #ec4899; --pink-bright: #f472b6;\r\n");
      out.write("    --blue: #3b82f6; --blue-bright: #60a5fa; --cyan: #22d3ee;\r\n");
      out.write("    --white: #f0eaff; --dim: #7c6fa0;\r\n");
      out.write("    --border: rgba(139,92,246,0.18); --border-bright: rgba(139,92,246,0.45);\r\n");
      out.write("}\r\n");
      out.write("* { box-sizing: border-box; margin: 0; padding: 0; }\r\n");
      out.write("body { background: var(--bg); color: var(--white); font-family: 'Inter', sans-serif; display: flex; min-height: 100vh; overflow-x: hidden; }\r\n");
      out.write(".blob { position: fixed; border-radius: 50%; filter: blur(120px); pointer-events: none; z-index: 0; opacity: 0.1; }\r\n");
      out.write(".blob-1 { width: 600px; height: 600px; background: var(--purple); top: -200px; left: -100px; }\r\n");
      out.write(".blob-2 { width: 500px; height: 500px; background: var(--pink); bottom: -150px; right: -50px; }\r\n");
      out.write(".blob-3 { width: 400px; height: 400px; background: var(--blue); top: 35%; left: 35%; }\r\n");
      out.write("\r\n");
      out.write("/* SIDEBAR */\r\n");
      out.write(".sidebar {\r\n");
      out.write("    width: var(--sidebar-w); height: 100vh; position: fixed; top: 0; left: 0;\r\n");
      out.write("    background: rgba(8,6,20,0.95); border-right: 1px solid var(--border);\r\n");
      out.write("    backdrop-filter: blur(20px); display: flex; flex-direction: column;\r\n");
      out.write("    padding: 28px 18px; z-index: 100;\r\n");
      out.write("}\r\n");
      out.write(".logo {\r\n");
      out.write("    font-family: 'Orbitron', sans-serif; font-size: 0.85rem; font-weight: 900;\r\n");
      out.write("    letter-spacing: 3px; text-align: center; padding: 10px 0 18px;\r\n");
      out.write("    background: linear-gradient(135deg, var(--purple-bright), var(--pink-bright), var(--blue-bright));\r\n");
      out.write("    -webkit-background-clip: text; -webkit-text-fill-color: transparent; background-clip: text;\r\n");
      out.write("}\r\n");
      out.write(".logo-divider {\r\n");
      out.write("    height: 1px; margin-bottom: 24px;\r\n");
      out.write("    background: linear-gradient(90deg, transparent, var(--purple), var(--pink), transparent);\r\n");
      out.write("}\r\n");
      out.write(".nav-section { margin-bottom: 28px; }\r\n");
      out.write(".nav-label {\r\n");
      out.write("    font-size: 0.58rem; font-family: 'Orbitron', sans-serif;\r\n");
      out.write("    text-transform: uppercase; letter-spacing: 3px; color: var(--dim);\r\n");
      out.write("    margin-bottom: 10px; padding-left: 14px; display: block;\r\n");
      out.write("}\r\n");
      out.write(".nav-item {\r\n");
      out.write("    display: flex; align-items: center; gap: 10px; padding: 11px 14px; border-radius: 10px;\r\n");
      out.write("    color: var(--dim); text-decoration: none; font-family: 'Rajdhani', sans-serif;\r\n");
      out.write("    font-size: 0.95rem; font-weight: 600; transition: all 0.25s; margin-bottom: 3px;\r\n");
      out.write("    border: none; background: none; cursor: pointer; width: 100%; text-align: left;\r\n");
      out.write("}\r\n");
      out.write(".nav-item:hover, .nav-item.active { background: rgba(139,92,246,0.12); color: var(--white); }\r\n");
      out.write(".nav-item.active { color: var(--purple-bright); }\r\n");
      out.write(".sidebar-footer {\r\n");
      out.write("    margin-top: auto;                /* keeps it at the bottom */\r\n");
      out.write("    border-top: 1px solid var(--border);\r\n");
      out.write("    padding: 14px;                   /* some padding for logout */\r\n");
      out.write("    display: flex;                   \r\n");
      out.write("    flex-direction: column;          \r\n");
      out.write("    gap: 12px;                       \r\n");
      out.write("    flex-shrink: 0;                  \r\n");
      out.write("}\r\n");
      out.write(".sidebar-footer .nav-item {\r\n");
      out.write("    width: 100%;                     /* ensures the logout link fills container */\r\n");
      out.write("    justify-content: flex-start;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".user-chip {\r\n");
      out.write("    display: flex; align-items: center; gap: 10px; padding: 11px 14px;\r\n");
      out.write("    border-radius: 10px; background: rgba(139,92,246,0.08);\r\n");
      out.write("    border: 1px solid var(--border); margin-bottom: 10px;\r\n");
      out.write("}\r\n");
      out.write(".user-avatar {\r\n");
      out.write("    width: 34px; height: 34px; border-radius: 50%;\r\n");
      out.write("    background: linear-gradient(135deg, var(--purple), var(--pink));\r\n");
      out.write("    display: flex; align-items: center; justify-content: center;\r\n");
      out.write("    font-size: 0.85rem; font-weight: 700; font-family: 'Orbitron', sans-serif; flex-shrink: 0;\r\n");
      out.write("}\r\n");
      out.write(".user-name { font-family: 'Rajdhani', sans-serif; font-weight: 700; font-size: 0.9rem; color: var(--purple-bright); }\r\n");
      out.write(".user-role { font-size: 0.62rem; color: var(--dim); }\r\n");
      out.write("\r\n");
      out.write("/* MAIN */\r\n");
      out.write(".main { margin-left: var(--sidebar-w); width: calc(100% - var(--sidebar-w)); min-height: 100vh; padding: 36px 40px; position: relative; z-index: 1; }\r\n");
      out.write("\r\n");
      out.write("/* TOP BAR */\r\n");
      out.write(".top-bar { display: flex; justify-content: space-between; align-items: center; margin-bottom: 36px; }\r\n");
      out.write(".page-title { font-family: 'Orbitron', sans-serif; font-size: 1.4rem; font-weight: 700; background: linear-gradient(90deg, var(--purple-bright), var(--pink-bright)); -webkit-background-clip: text; -webkit-text-fill-color: transparent; background-clip: text; }\r\n");
      out.write(".search-wrap { position: relative; }\r\n");
      out.write(".search-wrap input {\r\n");
      out.write("    background: var(--panel); border: 1px solid var(--border); border-radius: 10px;\r\n");
      out.write("    padding: 11px 20px 11px 44px; color: var(--white); font-family: 'Inter'; font-size: 0.85rem;\r\n");
      out.write("    width: 280px; outline: none; transition: all 0.3s;\r\n");
      out.write("}\r\n");
      out.write(".search-wrap input::placeholder { color: var(--dim); }\r\n");
      out.write(".search-wrap input:focus { border-color: var(--purple); box-shadow: 0 0 0 3px rgba(139,92,246,0.15); }\r\n");
      out.write(".search-icon { position: absolute; left: 15px; top: 50%; transform: translateY(-50%); color: var(--dim); }\r\n");
      out.write("\r\n");
      out.write("/* STATS */\r\n");
      out.write(".stats-row { display: grid; grid-template-columns: repeat(3, 1fr); gap: 18px; margin-bottom: 36px; }\r\n");
      out.write(".stat-card {\r\n");
      out.write("    background: var(--panel); border: 1px solid var(--border); border-radius: 16px;\r\n");
      out.write("    padding: 22px 24px; display: flex; align-items: center; gap: 18px;\r\n");
      out.write("    position: relative; overflow: hidden; transition: border-color 0.3s, transform 0.3s;\r\n");
      out.write("}\r\n");
      out.write(".stat-card:hover { border-color: var(--border-bright); transform: translateY(-3px); }\r\n");
      out.write(".stat-card::before { content: ''; position: absolute; top: 0; left: 0; right: 0; height: 2px; }\r\n");
      out.write(".c1::before { background: linear-gradient(90deg, var(--purple), var(--pink)); }\r\n");
      out.write(".c2::before { background: linear-gradient(90deg, var(--pink), var(--blue)); }\r\n");
      out.write(".c3::before { background: linear-gradient(90deg, var(--blue), var(--cyan)); }\r\n");
      out.write(".stat-icon-wrap { width: 50px; height: 50px; border-radius: 12px; display: flex; align-items: center; justify-content: center; font-size: 1.5rem; flex-shrink: 0; }\r\n");
      out.write(".c1 .stat-icon-wrap { background: rgba(139,92,246,0.15); }\r\n");
      out.write(".c2 .stat-icon-wrap { background: rgba(236,72,153,0.15); }\r\n");
      out.write(".c3 .stat-icon-wrap { background: rgba(59,130,246,0.15); }\r\n");
      out.write(".stat-val { font-family: 'Orbitron', sans-serif; font-size: 1.35rem; font-weight: 700; display: block; line-height: 1; }\r\n");
      out.write(".c1 .stat-val { color: var(--purple-bright); }\r\n");
      out.write(".c2 .stat-val { color: var(--pink-bright); }\r\n");
      out.write(".c3 .stat-val { color: var(--blue-bright); }\r\n");
      out.write(".stat-lbl { font-size: 0.7rem; color: var(--dim); font-family: 'Rajdhani'; letter-spacing: 1px; text-transform: uppercase; margin-top: 4px; display: block; }\r\n");
      out.write("\r\n");
      out.write("/* SECTION HEADER */\r\n");
      out.write(".section-header { display: flex; justify-content: space-between; align-items: center; margin-bottom: 24px; }\r\n");
      out.write(".section-title {\r\n");
      out.write("    font-family: 'Rajdhani', sans-serif; font-size: 1.1rem; font-weight: 700;\r\n");
      out.write("    display: flex; align-items: center; gap: 10px;\r\n");
      out.write("}\r\n");
      out.write(".section-title::before { content: ''; width: 4px; height: 18px; border-radius: 2px; background: linear-gradient(to bottom, var(--purple), var(--pink)); }\r\n");
      out.write(".btn-submit {\r\n");
      out.write("    display: inline-flex; align-items: center; gap: 8px; padding: 10px 22px; border-radius: 10px;\r\n");
      out.write("    background: linear-gradient(135deg, var(--purple), var(--pink));\r\n");
      out.write("    color: white; text-decoration: none; font-family: 'Rajdhani'; font-size: 0.9rem; font-weight: 700;\r\n");
      out.write("    border: none; cursor: pointer; transition: all 0.3s;\r\n");
      out.write("    box-shadow: 0 4px 20px rgba(139,92,246,0.3);\r\n");
      out.write("}\r\n");
      out.write(".btn-submit:hover { transform: translateY(-2px); box-shadow: 0 8px 30px rgba(139,92,246,0.5); }\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(".deco {\r\n");
      out.write("    display: inline-flex; align-items: center; gap: 8px; padding: 10px 22px; border-radius: 10px;\r\n");
      out.write("    background: linear-gradient(135deg, var(--purple), var(--pink));\r\n");
      out.write("    color: white; text-decoration: none; font-family: 'Rajdhani'; font-size: 0.9rem; font-weight: 700;\r\n");
      out.write("    border: none; cursor: pointer; transition: all 0.3s;\r\n");
      out.write("    box-shadow: 0 4px 20px rgba(139,92,246,0.3);\r\n");
      out.write("    align-self: flex-start;\r\n");
      out.write("    margin-left: 0;\r\n");
      out.write("}\r\n");
      out.write(".deco:hover { transform: translateY(-2px); box-shadow: 0 8px 30px rgba(139,92,246,0.5); }\r\n");
      out.write("\r\n");
      out.write(".logout-form {\r\n");
      out.write("    display: flex;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".logout-form .deco {\r\n");
      out.write("    margin-right: auto;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("/* MOD GRID */\r\n");
      out.write(".mod-grid { display: grid; grid-template-columns: repeat(auto-fill, minmax(290px, 1fr)); gap: 22px; }\r\n");
      out.write(".mod-card {\r\n");
      out.write("    background: var(--panel); border: 1px solid var(--border); border-radius: 16px;\r\n");
      out.write("    overflow: hidden; transition: all 0.35s; position: relative;\r\n");
      out.write("    animation: fadeUp 0.5s ease both;\r\n");
      out.write("}\r\n");
      out.write(".mod-card:hover { transform: translateY(-8px); border-color: rgba(139,92,246,0.5); box-shadow: 0 20px 60px rgba(0,0,0,0.5), 0 0 30px rgba(139,92,246,0.15); }\r\n");
      out.write(".card-img-wrap { position: relative; overflow: hidden; height: 165px; }\r\n");
      out.write(".card-img { width: 100%; height: 100%; object-fit: cover; transition: transform 0.5s, filter 0.5s; filter: brightness(0.7) saturate(1.2); }\r\n");
      out.write(".mod-card:hover .card-img { transform: scale(1.08); filter: brightness(0.9) saturate(1.5); }\r\n");
      out.write(".card-overlay { position: absolute; inset: 0; background: linear-gradient(to top, var(--panel) 0%, transparent 60%); }\r\n");
      out.write(".badge {\r\n");
      out.write("    position: absolute; top: 10px; left: 10px; padding: 4px 10px; border-radius: 6px;\r\n");
      out.write("    font-family: 'Orbitron'; font-size: 0.55rem; font-weight: 700; letter-spacing: 1.5px;\r\n");
      out.write("    background: linear-gradient(135deg, #ec4899, #f43f5e); color: white;\r\n");
      out.write("    box-shadow: 0 0 15px rgba(236,72,153,0.6);\r\n");
      out.write("}\r\n");
      out.write(".card-cat {\r\n");
      out.write("    position: absolute; top: 10px; right: 10px; padding: 3px 8px; border-radius: 5px;\r\n");
      out.write("    font-size: 0.6rem; font-family: 'Rajdhani'; font-weight: 700; letter-spacing: 1px;\r\n");
      out.write("    background: rgba(139,92,246,0.3); border: 1px solid rgba(139,92,246,0.4);\r\n");
      out.write("    color: var(--purple-bright); backdrop-filter: blur(8px);\r\n");
      out.write("}\r\n");
      out.write(".card-body { padding: 18px 20px; }\r\n");
      out.write(".card-title { font-family: 'Rajdhani'; font-size: 1.05rem; font-weight: 700; color: var(--white); margin-bottom: 8px; line-height: 1.3; }\r\n");
      out.write(".card-meta { display: flex; justify-content: space-between; align-items: center; margin-bottom: 14px; }\r\n");
      out.write(".card-author { font-size: 0.75rem; color: var(--dim); }\r\n");
      out.write(".card-dl { font-size: 0.75rem; color: var(--pink-bright); font-family: 'Orbitron'; }\r\n");
      out.write(".card-actions { display: flex; gap: 8px; }\r\n");
      out.write(".btn-card {\r\n");
      out.write("    flex: 1; padding: 9px 6px; border-radius: 8px; font-family: 'Rajdhani';\r\n");
      out.write("    font-size: 0.8rem; font-weight: 700; cursor: pointer; transition: all 0.25s;\r\n");
      out.write("    border: 1px solid; text-align: center; text-decoration: none;\r\n");
      out.write("    display: flex; align-items: center; justify-content: center;\r\n");
      out.write("}\r\n");
      out.write(".btn-view { background: transparent; border-color: rgba(139,92,246,0.4); color: var(--purple-bright); }\r\n");
      out.write(".btn-view:hover { background: rgba(139,92,246,0.15); border-color: var(--purple); }\r\n");
      out.write(".btn-edit { background: transparent; border-color: rgba(59,130,246,0.4); color: var(--blue-bright); }\r\n");
      out.write(".btn-edit:hover { background: rgba(59,130,246,0.12); border-color: var(--blue); }\r\n");
      out.write(".btn-del-form { flex: 1; }\r\n");
      out.write(".btn-del-form button { width: 100%; background: transparent; border: 1px solid rgba(236,72,153,0.35); border-radius: 8px; color: var(--pink); padding: 9px 6px; font-family: 'Rajdhani'; font-size: 0.8rem; font-weight: 700; cursor: pointer; transition: all 0.25s; }\r\n");
      out.write(".btn-del-form button:hover { background: rgba(236,72,153,0.1); border-color: var(--pink); }\r\n");
      out.write(".empty-state { grid-column: 1/-1; text-align: center; padding: 80px 20px; color: var(--dim); }\r\n");
      out.write(".empty-state .ei { font-size: 4rem; margin-bottom: 16px; }\r\n");
      out.write(".empty-state p { font-family: 'Rajdhani'; font-size: 1.1rem; }\r\n");
      out.write("::-webkit-scrollbar { width: 5px; }\r\n");
      out.write("::-webkit-scrollbar-track { background: var(--bg); }\r\n");
      out.write("::-webkit-scrollbar-thumb { background: linear-gradient(var(--purple), var(--pink)); border-radius: 99px; }\r\n");
      out.write("@keyframes fadeUp { from { opacity: 0; transform: translateY(20px); } to { opacity: 1; transform: translateY(0); } }\r\n");
      out.write(".mod-card:nth-child(1){animation-delay:0.05s} .mod-card:nth-child(2){animation-delay:0.10s}\r\n");
      out.write(".mod-card:nth-child(3){animation-delay:0.15s} .mod-card:nth-child(4){animation-delay:0.20s}\r\n");
      out.write(".mod-card:nth-child(5){animation-delay:0.25s} .mod-card:nth-child(6){animation-delay:0.30s}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<div class=\"blob blob-1\"></div>\r\n");
      out.write("<div class=\"blob blob-2\"></div>\r\n");
      out.write("<div class=\"blob blob-3\"></div>\r\n");
      out.write("\r\n");
      out.write("<aside class=\"sidebar\">\r\n");
      out.write("    <div class=\"logo\">⚡ GAMEVERSE ACADEMY</div>\r\n");
      out.write("    <div class=\"logo-divider\"></div>\r\n");
      out.write("    <a href=\"reviews\" class=\"nav-item\">⭐ Reviews</a>\r\n");
      out.write("\r\n");
      out.write("    <nav class=\"nav-section\">\r\n");
      out.write("        <span class=\"nav-label\">Navigation</span>\r\n");
      out.write("        <a href=\"mods\" class=\"nav-item ");
      out.print( currentCategory == null ? "active" : "" );
      out.write("\">🏠 Dashboard</a>\r\n");
      out.write("        <a href=\"ModSubmitController\" class=\"nav-item\">➕ Submit a Mod</a>\r\n");
      out.write("    </nav>\r\n");
      out.write("\r\n");
      out.write("    <nav class=\"nav-section\">\r\n");
      out.write("        <span class=\"nav-label\">Categories</span>\r\n");
      out.write("        <a href=\"mods?category=Graphique\" class=\"nav-item ");
      out.print( "Graphique".equals(currentCategory) ? "active" : "" );
      out.write("\">🎨 Graphics</a>\r\n");
      out.write("        <a href=\"mods?category=Gameplay\" class=\"nav-item ");
      out.print( "Gameplay".equals(currentCategory) ? "active" : "" );
      out.write("\">🕹️ Gameplay</a>\r\n");
      out.write("        <a href=\"mods?category=Map\" class=\"nav-item ");
      out.print( "Map".equals(currentCategory) ? "active" : "" );
      out.write("\">🗺️ Maps</a>\r\n");
      out.write("        <a href=\"mods?category=Script\" class=\"nav-item ");
      out.print( "Script".equals(currentCategory) ? "active" : "" );
      out.write("\">📜 Scripts</a>\r\n");
      out.write("    </nav>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"sidebar-footer\">\r\n");
      out.write("            <div style=\"margin-top: auto;\">\r\n");
      out.write("            	<a href=\"index.html\" class=\"nav-item\"><span>🚪</span> Logout</a>\r\n");
      out.write("       		</div>\r\n");
      out.write("        \r\n");
      out.write("        <div class=\"user-chip\">\r\n");
      out.write("            <div class=\"user-avatar\">");
      out.print( userLogin != null ? userLogin.substring(0,1).toUpperCase() : "G" );
      out.write("</div>\r\n");
      out.write("            <div>\r\n");
      out.write("                <div class=\"user-name\">");
      out.print( userLogin != null ? userLogin : "Guest" );
      out.write("</div>\r\n");
      out.write("                <div class=\"user-role\">Mod Creator</div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("</aside>\r\n");
      out.write("\r\n");
      out.write("<main class=\"main\">\r\n");
      out.write("    <div class=\"top-bar\">\r\n");
      out.write("        <div class=\"page-title\">");
      out.print( currentCategory != null ? currentCategory : "All Mods" );
      out.write("</div>\r\n");
      out.write("        <div class=\"search-wrap\">\r\n");
      out.write("            <span class=\"search-icon\">🔍</span>\r\n");
      out.write("            <input type=\"text\" id=\"modSearch\" placeholder=\"Search mods...\" onkeyup=\"filterMods()\">\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                    <div class=\"user-info\">\r\n");
      out.write("				    <i class=\"bi bi-person-circle\"></i>\r\n");
      out.write("				    <span>\r\n");
      out.write("				        ");
      out.print( session.getAttribute("user") != null
				              ? session.getAttribute("user") : "Visiteur" );
      out.write("\r\n");
      out.write("				    </span>\r\n");
      out.write("				</div >\r\n");
      out.write("				<form class=\"logout-form\" action=\"");
      out.print( request.getContextPath() );
      out.write("/LogoutController\" method=\"post\">\r\n");
      out.write("				    <button type=\"submit\" class=\"deco\">\r\n");
      out.write("				        <i class=\"bi bi-box-arrow-right\"></i> Déconnexion\r\n");
      out.write("				    </button>\r\n");
      out.write("				</form>\r\n");
      out.write("				\r\n");
      out.write("				\r\n");
      out.write("				\r\n");
      out.write("    <div class=\"stats-row\">\r\n");
      out.write("        <div class=\"stat-card c1\">\r\n");
      out.write("            <div class=\"stat-icon-wrap\">📦</div>\r\n");
      out.write("            <div><span class=\"stat-val\">");
      out.print( mods != null ? mods.size() : 0 );
      out.write("</span><span class=\"stat-lbl\">Active Mods</span></div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"stat-card c2\">\r\n");
      out.write("            <div class=\"stat-icon-wrap\">🔥</div>\r\n");
      out.write("            <div><span class=\"stat-val\">Trending</span><span class=\"stat-lbl\">Top Community Picks</span></div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"stat-card c3\">\r\n");
      out.write("            <div class=\"stat-icon-wrap\">💎</div>\r\n");
      out.write("            <div><span class=\"stat-val\">Verified</span><span class=\"stat-lbl\">Official Academy Content</span></div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"section-header\">\r\n");
      out.write("        <div class=\"section-title\">Browse Mods</div>\r\n");
      out.write("        <a href=\"ModSubmitController\" class=\"btn-submit\">➕ Submit Mod</a>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"mod-grid\" id=\"modGrid\">\r\n");
      out.write("        ");
 if (mods != null && !mods.isEmpty()) {
            for (Mod m : mods) {
                String foundImg = fallbackImg;
                String t = m.getTitle().toLowerCase();
                for (String key : gameImages.keySet()) { if (t.contains(key)) { foundImg = gameImages.get(key); break; } }
        
      out.write("\r\n");
      out.write("        <div class=\"mod-card mod-item\" data-title=\"");
      out.print( m.getTitle().toLowerCase() );
      out.write("\">\r\n");
      out.write("            <div class=\"card-img-wrap\">\r\n");
      out.write("                <img src=\"");
      out.print( foundImg );
      out.write("\" class=\"card-img\" alt=\"cover\">\r\n");
      out.write("                <div class=\"card-overlay\"></div>\r\n");
      out.write("                ");
 if (m.getDownloads() > 500) { 
      out.write("<div class=\"badge\">🔥 TRENDING</div>");
 } 
      out.write("\r\n");
      out.write("                ");
 if (m.getCategory() != null) { 
      out.write("<div class=\"card-cat\">");
      out.print( m.getCategory() );
      out.write("</div>");
 } 
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"card-body\">\r\n");
      out.write("                <div class=\"card-title\">");
      out.print( m.getTitle() );
      out.write("</div>\r\n");
      out.write("                <div class=\"card-meta\">\r\n");
      out.write("                    <span class=\"card-author\">👤 ");
      out.print( m.getAuthor() != null ? m.getAuthor() : "Unknown" );
      out.write("</span>\r\n");
      out.write("                    <span class=\"card-dl\">📥 ");
      out.print( m.getDownloads() );
      out.write("</span>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"card-actions\">\r\n");
      out.write("                    <button class=\"btn-card btn-view\">👁 View</button>\r\n");
      out.write("                    <a href=\"");
      out.print( request.getContextPath() );
      out.write("/ModEditController?id=");
      out.print( m.getId() );
      out.write("\" class=\"btn-card btn-edit\">✏️ Edit</a>\r\n");
      out.write("                    <form action=\"");
      out.print( request.getContextPath() );
      out.write("/ModDeleteController\" method=\"post\" class=\"btn-del-form\">\r\n");
      out.write("                        <input type=\"hidden\" name=\"id\" value=\"");
      out.print( m.getId() );
      out.write("\">\r\n");
      out.write("                        <button type=\"submit\">🗑 Delete</button>\r\n");
      out.write("                    </form>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        ");
 } } else { 
      out.write("\r\n");
      out.write("        <div class=\"empty-state\"><div class=\"ei\">🎮</div><p>No mods found. Be the first to submit one!</p></div>\r\n");
      out.write("        ");
 } 
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("</main>\r\n");
      out.write("<script>\r\n");
      out.write("function filterMods() {\r\n");
      out.write("    const q = document.getElementById('modSearch').value.toLowerCase();\r\n");
      out.write("    document.querySelectorAll('.mod-item').forEach(el => { el.style.display = el.dataset.title.includes(q) ? '' : 'none'; });\r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
