/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.18
 * Generated at: 2026-04-23 11:04:53 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import java.util.*;
import ma.ac.esi.gameverseacademy.model.Mod;

public final class review_002dform_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("ma.ac.esi.gameverseacademy.model.Mod");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

    List<Mod> mods = (List<Mod>) request.getAttribute("mods");
    String userLogin = (String) session.getAttribute("login");
    int userId = session.getAttribute("userId") != null ? (int) session.getAttribute("userId") : 1;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("<title>GameVerse Academy — Add Review</title>\r\n");
      out.write("<link href=\"https://fonts.googleapis.com/css2?family=Rajdhani:wght@400;500;600;700&family=Orbitron:wght@400;600;700;900&family=Inter:wght@300;400;500&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("<style>\r\n");
      out.write(":root {\r\n");
      out.write("    --sidebar-w: 270px;\r\n");
      out.write("    --bg: #07050f; --bg2: #0d0a1a; --panel: #110e22; --panel2: #1a1530;\r\n");
      out.write("    --purple: #8b5cf6; --purple-bright: #a78bfa;\r\n");
      out.write("    --pink: #ec4899; --pink-bright: #f472b6;\r\n");
      out.write("    --blue: #3b82f6; --blue-bright: #60a5fa; --cyan: #22d3ee;\r\n");
      out.write("    --amber: #f59e0b;\r\n");
      out.write("    --white: #f0eaff; --dim: #7c6fa0;\r\n");
      out.write("    --border: rgba(139,92,246,0.18); --border-bright: rgba(139,92,246,0.45);\r\n");
      out.write("}\r\n");
      out.write("* { box-sizing: border-box; margin: 0; padding: 0; }\r\n");
      out.write("body { background: var(--bg); color: var(--white); font-family: 'Inter', sans-serif; display: flex; min-height: 100vh; overflow-x: hidden; }\r\n");
      out.write(".blob { position: fixed; border-radius: 50%; filter: blur(120px); pointer-events: none; z-index: 0; opacity: 0.1; }\r\n");
      out.write(".blob-1 { width: 600px; height: 600px; background: var(--purple); top: -200px; left: -100px; }\r\n");
      out.write(".blob-2 { width: 500px; height: 500px; background: var(--pink); bottom: -150px; right: -50px; }\r\n");
      out.write(".sidebar { width: var(--sidebar-w); height: 100vh; position: fixed; top: 0; left: 0; background: rgba(8,6,20,0.95); border-right: 1px solid var(--border); backdrop-filter: blur(20px); display: flex; flex-direction: column; padding: 28px 18px; z-index: 100; }\r\n");
      out.write(".logo { font-family: 'Orbitron', sans-serif; font-size: 0.85rem; font-weight: 900; letter-spacing: 3px; text-align: center; padding: 10px 0 18px; background: linear-gradient(135deg, var(--purple-bright), var(--pink-bright), var(--blue-bright)); -webkit-background-clip: text; -webkit-text-fill-color: transparent; background-clip: text; }\r\n");
      out.write(".logo-divider { height: 1px; margin-bottom: 24px; background: linear-gradient(90deg, transparent, var(--purple), var(--pink), transparent); }\r\n");
      out.write(".nav-section { margin-bottom: 28px; }\r\n");
      out.write(".nav-label { font-size: 0.58rem; font-family: 'Orbitron', sans-serif; text-transform: uppercase; letter-spacing: 3px; color: var(--dim); margin-bottom: 10px; padding-left: 14px; display: block; }\r\n");
      out.write(".nav-item { display: flex; align-items: center; gap: 10px; padding: 11px 14px; border-radius: 10px; color: var(--dim); text-decoration: none; font-family: 'Rajdhani', sans-serif; font-size: 0.95rem; font-weight: 600; transition: all 0.25s; margin-bottom: 3px; border: none; background: none; cursor: pointer; width: 100%; text-align: left; }\r\n");
      out.write(".nav-item:hover, .nav-item.active { background: rgba(139,92,246,0.12); color: var(--white); }\r\n");
      out.write(".nav-item.active { color: var(--purple-bright); }\r\n");
      out.write(".sidebar-footer { margin-top: auto; border-top: 1px solid var(--border); padding: 14px; display: flex; flex-direction: column; gap: 12px; flex-shrink: 0; }\r\n");
      out.write(".user-chip { display: flex; align-items: center; gap: 10px; padding: 11px 14px; border-radius: 10px; background: rgba(139,92,246,0.08); border: 1px solid var(--border); }\r\n");
      out.write(".user-avatar { width: 34px; height: 34px; border-radius: 50%; background: linear-gradient(135deg, var(--purple), var(--pink)); display: flex; align-items: center; justify-content: center; font-size: 0.85rem; font-weight: 700; font-family: 'Orbitron'; flex-shrink: 0; }\r\n");
      out.write(".user-name { font-family: 'Rajdhani'; font-weight: 700; font-size: 0.9rem; color: var(--purple-bright); }\r\n");
      out.write(".user-role { font-size: 0.62rem; color: var(--dim); }\r\n");
      out.write(".main { margin-left: var(--sidebar-w); width: calc(100% - var(--sidebar-w)); min-height: 100vh; padding: 36px 40px; position: relative; z-index: 1; display: flex; flex-direction: column; align-items: center; justify-content: flex-start; }\r\n");
      out.write(".page-title { font-family: 'Orbitron', sans-serif; font-size: 1.4rem; font-weight: 700; background: linear-gradient(90deg, var(--purple-bright), var(--pink-bright)); -webkit-background-clip: text; -webkit-text-fill-color: transparent; background-clip: text; margin-bottom: 36px; align-self: flex-start; }\r\n");
      out.write("\r\n");
      out.write("/* FORM CARD */\r\n");
      out.write(".form-card { background: var(--panel); border: 1px solid var(--border); border-radius: 20px; padding: 40px; width: 100%; max-width: 640px; position: relative; overflow: hidden; }\r\n");
      out.write(".form-card::before { content: ''; position: absolute; top: 0; left: 0; right: 0; height: 3px; background: linear-gradient(90deg, var(--purple), var(--pink), var(--blue)); }\r\n");
      out.write("\r\n");
      out.write(".form-group { margin-bottom: 24px; }\r\n");
      out.write(".form-label { display: block; font-family: 'Rajdhani'; font-size: 0.8rem; font-weight: 700; letter-spacing: 2px; text-transform: uppercase; color: var(--dim); margin-bottom: 10px; }\r\n");
      out.write(".form-control { width: 100%; background: rgba(139,92,246,0.06); border: 1px solid var(--border); border-radius: 10px; padding: 13px 16px; color: var(--white); font-family: 'Inter'; font-size: 0.9rem; outline: none; transition: all 0.3s; }\r\n");
      out.write(".form-control:focus { border-color: var(--purple); box-shadow: 0 0 0 3px rgba(139,92,246,0.15); background: rgba(139,92,246,0.1); }\r\n");
      out.write(".form-control option { background: #110e22; color: var(--white); }\r\n");
      out.write("textarea.form-control { resize: vertical; min-height: 120px; }\r\n");
      out.write("\r\n");
      out.write("/* STAR RATING */\r\n");
      out.write(".star-rating { display: flex; gap: 8px; flex-direction: row-reverse; justify-content: flex-end; }\r\n");
      out.write(".star-rating input { display: none; }\r\n");
      out.write(".star-rating label { font-size: 2rem; color: rgba(139,92,246,0.2); cursor: pointer; transition: color 0.2s, transform 0.2s; }\r\n");
      out.write(".star-rating label:hover,\r\n");
      out.write(".star-rating label:hover ~ label,\r\n");
      out.write(".star-rating input:checked ~ label { color: var(--amber); }\r\n");
      out.write(".star-rating label:hover { transform: scale(1.2); }\r\n");
      out.write("\r\n");
      out.write("/* BUTTONS */\r\n");
      out.write(".form-actions { display: flex; gap: 12px; margin-top: 32px; }\r\n");
      out.write(".btn-submit { flex: 1; padding: 14px; border-radius: 10px; background: linear-gradient(135deg, var(--purple), var(--pink)); color: white; font-family: 'Rajdhani'; font-size: 1rem; font-weight: 700; border: none; cursor: pointer; transition: all 0.3s; box-shadow: 0 4px 20px rgba(139,92,246,0.3); letter-spacing: 1px; }\r\n");
      out.write(".btn-submit:hover { transform: translateY(-2px); box-shadow: 0 8px 30px rgba(139,92,246,0.5); }\r\n");
      out.write(".btn-cancel { padding: 14px 24px; border-radius: 10px; background: transparent; border: 1px solid var(--border); color: var(--dim); font-family: 'Rajdhani'; font-size: 1rem; font-weight: 700; cursor: pointer; transition: all 0.3s; text-decoration: none; display: flex; align-items: center; }\r\n");
      out.write(".btn-cancel:hover { border-color: var(--purple); color: var(--white); }\r\n");
      out.write("\r\n");
      out.write("::-webkit-scrollbar { width: 5px; }\r\n");
      out.write("::-webkit-scrollbar-track { background: var(--bg); }\r\n");
      out.write("::-webkit-scrollbar-thumb { background: linear-gradient(var(--purple), var(--pink)); border-radius: 99px; }\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<div class=\"blob blob-1\"></div>\r\n");
      out.write("<div class=\"blob blob-2\"></div>\r\n");
      out.write("\r\n");
      out.write("<aside class=\"sidebar\">\r\n");
      out.write("    <div class=\"logo\">⚡ GAMEVERSE ACADEMY</div>\r\n");
      out.write("    <div class=\"logo-divider\"></div>\r\n");
      out.write("    <nav class=\"nav-section\">\r\n");
      out.write("        <span class=\"nav-label\">Navigation</span>\r\n");
      out.write("        <a href=\"mods\" class=\"nav-item\">🏠 Dashboard</a>\r\n");
      out.write("        <a href=\"ModSubmitController\" class=\"nav-item\">➕ Submit a Mod</a>\r\n");
      out.write("        <a href=\"reviews\" class=\"nav-item active\">⭐ Reviews</a>\r\n");
      out.write("    </nav>\r\n");
      out.write("    <nav class=\"nav-section\">\r\n");
      out.write("        <span class=\"nav-label\">Categories</span>\r\n");
      out.write("        <a href=\"mods?category=Graphique\" class=\"nav-item\">🎨 Graphics</a>\r\n");
      out.write("        <a href=\"mods?category=Gameplay\" class=\"nav-item\">🕹️ Gameplay</a>\r\n");
      out.write("        <a href=\"mods?category=Map\" class=\"nav-item\">🗺️ Maps</a>\r\n");
      out.write("        <a href=\"mods?category=Script\" class=\"nav-item\">📜 Scripts</a>\r\n");
      out.write("    </nav>\r\n");
      out.write("    <div class=\"sidebar-footer\">\r\n");
      out.write("        <a href=\"index.html\" class=\"nav-item\">🚪 Logout</a>\r\n");
      out.write("        <div class=\"user-chip\">\r\n");
      out.write("            <div class=\"user-avatar\">");
      out.print( userLogin != null ? userLogin.substring(0,1).toUpperCase() : "G" );
      out.write("</div>\r\n");
      out.write("            <div>\r\n");
      out.write("                <div class=\"user-name\">");
      out.print( userLogin != null ? userLogin : "Guest" );
      out.write("</div>\r\n");
      out.write("                <div class=\"user-role\">Mod Creator</div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</aside>\r\n");
      out.write("\r\n");
      out.write("<main class=\"main\">\r\n");
      out.write("    <div class=\"page-title\">➕ Add a Review</div>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"form-card\">\r\n");
      out.write("        <form action=\"");
      out.print( request.getContextPath() );
      out.write("/ReviewAddController\" method=\"post\">\r\n");
      out.write("            <input type=\"hidden\" name=\"userId\" value=\"");
      out.print( userId );
      out.write("\">\r\n");
      out.write("\r\n");
      out.write("            <!-- MOD SELECT -->\r\n");
      out.write("            <div class=\"form-group\">\r\n");
      out.write("                <label class=\"form-label\">Select Mod</label>\r\n");
      out.write("                <select name=\"modId\" class=\"form-control\" required>\r\n");
      out.write("                    <option value=\"\">— Choose a mod —</option>\r\n");
      out.write("                    ");
 if (mods != null) { for (Mod m : mods) { 
      out.write("\r\n");
      out.write("                        <option value=\"");
      out.print( m.getId() );
      out.write('"');
      out.write('>');
      out.print( m.getTitle() );
      out.write("</option>\r\n");
      out.write("                    ");
 } } 
      out.write("\r\n");
      out.write("                </select>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <!-- STAR RATING -->\r\n");
      out.write("            <div class=\"form-group\">\r\n");
      out.write("                <label class=\"form-label\">Rating</label>\r\n");
      out.write("                <div class=\"star-rating\">\r\n");
      out.write("                    <input type=\"radio\" id=\"s5\" name=\"rating\" value=\"5\"><label for=\"s5\">★</label>\r\n");
      out.write("                    <input type=\"radio\" id=\"s4\" name=\"rating\" value=\"4\"><label for=\"s4\">★</label>\r\n");
      out.write("                    <input type=\"radio\" id=\"s3\" name=\"rating\" value=\"3\" checked><label for=\"s3\">★</label>\r\n");
      out.write("                    <input type=\"radio\" id=\"s2\" name=\"rating\" value=\"2\"><label for=\"s2\">★</label>\r\n");
      out.write("                    <input type=\"radio\" id=\"s1\" name=\"rating\" value=\"1\"><label for=\"s1\">★</label>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <!-- COMMENT -->\r\n");
      out.write("            <div class=\"form-group\">\r\n");
      out.write("                <label class=\"form-label\">Comment</label>\r\n");
      out.write("                <textarea name=\"comment\" class=\"form-control\" placeholder=\"Share your thoughts about this mod...\"></textarea>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <!-- ACTIONS -->\r\n");
      out.write("            <div class=\"form-actions\">\r\n");
      out.write("                <a href=\"");
      out.print( request.getContextPath() );
      out.write("/reviews\" class=\"btn-cancel\">✕ Cancel</a>\r\n");
      out.write("                <button type=\"submit\" class=\"btn-submit\">⭐ Submit Review</button>\r\n");
      out.write("            </div>\r\n");
      out.write("        </form>\r\n");
      out.write("    </div>\r\n");
      out.write("</main>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
