/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.18
 * Generated at: 2026-04-22 23:31:25 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import java.util.*;
import ma.ac.esi.gameverseacademy.model.Review;

public final class reviews_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("ma.ac.esi.gameverseacademy.model.Review");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

    List<Review> reviews = (List<Review>) request.getAttribute("reviews");
    String userLogin = (String) session.getAttribute("login");

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("<title>GameVerse Academy — Reviews</title>\r\n");
      out.write("<link href=\"https://fonts.googleapis.com/css2?family=Rajdhani:wght@400;500;600;700&family=Orbitron:wght@400;600;700;900&family=Inter:wght@300;400;500&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("<style>\r\n");
      out.write(":root {\r\n");
      out.write("    --sidebar-w: 270px;\r\n");
      out.write("    --bg: #07050f; --bg2: #0d0a1a; --panel: #110e22; --panel2: #1a1530;\r\n");
      out.write("    --purple: #8b5cf6; --purple-bright: #a78bfa;\r\n");
      out.write("    --pink: #ec4899; --pink-bright: #f472b6;\r\n");
      out.write("    --blue: #3b82f6; --blue-bright: #60a5fa; --cyan: #22d3ee;\r\n");
      out.write("    --green: #10b981; --amber: #f59e0b;\r\n");
      out.write("    --white: #f0eaff; --dim: #7c6fa0;\r\n");
      out.write("    --border: rgba(139,92,246,0.18); --border-bright: rgba(139,92,246,0.45);\r\n");
      out.write("}\r\n");
      out.write("* { box-sizing: border-box; margin: 0; padding: 0; }\r\n");
      out.write("body { background: var(--bg); color: var(--white); font-family: 'Inter', sans-serif; display: flex; min-height: 100vh; overflow-x: hidden; }\r\n");
      out.write(".blob { position: fixed; border-radius: 50%; filter: blur(120px); pointer-events: none; z-index: 0; opacity: 0.1; }\r\n");
      out.write(".blob-1 { width: 600px; height: 600px; background: var(--purple); top: -200px; left: -100px; }\r\n");
      out.write(".blob-2 { width: 500px; height: 500px; background: var(--pink); bottom: -150px; right: -50px; }\r\n");
      out.write(".blob-3 { width: 400px; height: 400px; background: var(--blue); top: 35%; left: 35%; }\r\n");
      out.write("\r\n");
      out.write("/* SIDEBAR */\r\n");
      out.write(".sidebar {\r\n");
      out.write("    width: var(--sidebar-w); height: 100vh; position: fixed; top: 0; left: 0;\r\n");
      out.write("    background: rgba(8,6,20,0.95); border-right: 1px solid var(--border);\r\n");
      out.write("    backdrop-filter: blur(20px); display: flex; flex-direction: column;\r\n");
      out.write("    padding: 28px 18px; z-index: 100;\r\n");
      out.write("}\r\n");
      out.write(".logo {\r\n");
      out.write("    font-family: 'Orbitron', sans-serif; font-size: 0.85rem; font-weight: 900;\r\n");
      out.write("    letter-spacing: 3px; text-align: center; padding: 10px 0 18px;\r\n");
      out.write("    background: linear-gradient(135deg, var(--purple-bright), var(--pink-bright), var(--blue-bright));\r\n");
      out.write("    -webkit-background-clip: text; -webkit-text-fill-color: transparent; background-clip: text;\r\n");
      out.write("}\r\n");
      out.write(".logo-divider { height: 1px; margin-bottom: 24px; background: linear-gradient(90deg, transparent, var(--purple), var(--pink), transparent); }\r\n");
      out.write(".nav-section { margin-bottom: 28px; }\r\n");
      out.write(".nav-label { font-size: 0.58rem; font-family: 'Orbitron', sans-serif; text-transform: uppercase; letter-spacing: 3px; color: var(--dim); margin-bottom: 10px; padding-left: 14px; display: block; }\r\n");
      out.write(".nav-item { display: flex; align-items: center; gap: 10px; padding: 11px 14px; border-radius: 10px; color: var(--dim); text-decoration: none; font-family: 'Rajdhani', sans-serif; font-size: 0.95rem; font-weight: 600; transition: all 0.25s; margin-bottom: 3px; border: none; background: none; cursor: pointer; width: 100%; text-align: left; }\r\n");
      out.write(".nav-item:hover, .nav-item.active { background: rgba(139,92,246,0.12); color: var(--white); }\r\n");
      out.write(".nav-item.active { color: var(--purple-bright); }\r\n");
      out.write(".sidebar-footer { margin-top: auto; border-top: 1px solid var(--border); padding: 14px; display: flex; flex-direction: column; gap: 12px; flex-shrink: 0; }\r\n");
      out.write(".user-chip { display: flex; align-items: center; gap: 10px; padding: 11px 14px; border-radius: 10px; background: rgba(139,92,246,0.08); border: 1px solid var(--border); }\r\n");
      out.write(".user-avatar { width: 34px; height: 34px; border-radius: 50%; background: linear-gradient(135deg, var(--purple), var(--pink)); display: flex; align-items: center; justify-content: center; font-size: 0.85rem; font-weight: 700; font-family: 'Orbitron', sans-serif; flex-shrink: 0; }\r\n");
      out.write(".user-name { font-family: 'Rajdhani', sans-serif; font-weight: 700; font-size: 0.9rem; color: var(--purple-bright); }\r\n");
      out.write(".user-role { font-size: 0.62rem; color: var(--dim); }\r\n");
      out.write("\r\n");
      out.write("/* MAIN */\r\n");
      out.write(".main { margin-left: var(--sidebar-w); width: calc(100% - var(--sidebar-w)); min-height: 100vh; padding: 36px 40px; position: relative; z-index: 1; }\r\n");
      out.write("\r\n");
      out.write("/* TOP BAR */\r\n");
      out.write(".top-bar { display: flex; justify-content: space-between; align-items: center; margin-bottom: 36px; }\r\n");
      out.write(".page-title { font-family: 'Orbitron', sans-serif; font-size: 1.4rem; font-weight: 700; background: linear-gradient(90deg, var(--purple-bright), var(--pink-bright)); -webkit-background-clip: text; -webkit-text-fill-color: transparent; background-clip: text; }\r\n");
      out.write("\r\n");
      out.write("/* STATS */\r\n");
      out.write(".stats-row { display: grid; grid-template-columns: repeat(3, 1fr); gap: 18px; margin-bottom: 36px; }\r\n");
      out.write(".stat-card { background: var(--panel); border: 1px solid var(--border); border-radius: 16px; padding: 22px 24px; display: flex; align-items: center; gap: 18px; position: relative; overflow: hidden; transition: border-color 0.3s, transform 0.3s; }\r\n");
      out.write(".stat-card:hover { border-color: var(--border-bright); transform: translateY(-3px); }\r\n");
      out.write(".stat-card::before { content: ''; position: absolute; top: 0; left: 0; right: 0; height: 2px; }\r\n");
      out.write(".c1::before { background: linear-gradient(90deg, var(--purple), var(--pink)); }\r\n");
      out.write(".c2::before { background: linear-gradient(90deg, var(--pink), var(--blue)); }\r\n");
      out.write(".c3::before { background: linear-gradient(90deg, var(--blue), var(--cyan)); }\r\n");
      out.write(".stat-icon-wrap { width: 50px; height: 50px; border-radius: 12px; display: flex; align-items: center; justify-content: center; font-size: 1.5rem; flex-shrink: 0; }\r\n");
      out.write(".c1 .stat-icon-wrap { background: rgba(139,92,246,0.15); }\r\n");
      out.write(".c2 .stat-icon-wrap { background: rgba(236,72,153,0.15); }\r\n");
      out.write(".c3 .stat-icon-wrap { background: rgba(59,130,246,0.15); }\r\n");
      out.write(".stat-val { font-family: 'Orbitron', sans-serif; font-size: 1.35rem; font-weight: 700; display: block; line-height: 1; }\r\n");
      out.write(".c1 .stat-val { color: var(--purple-bright); }\r\n");
      out.write(".c2 .stat-val { color: var(--pink-bright); }\r\n");
      out.write(".c3 .stat-val { color: var(--blue-bright); }\r\n");
      out.write(".stat-lbl { font-size: 0.7rem; color: var(--dim); font-family: 'Rajdhani'; letter-spacing: 1px; text-transform: uppercase; margin-top: 4px; display: block; }\r\n");
      out.write("\r\n");
      out.write("/* SECTION HEADER */\r\n");
      out.write(".section-header { display: flex; justify-content: space-between; align-items: center; margin-bottom: 24px; }\r\n");
      out.write(".section-title { font-family: 'Rajdhani', sans-serif; font-size: 1.1rem; font-weight: 700; display: flex; align-items: center; gap: 10px; }\r\n");
      out.write(".section-title::before { content: ''; width: 4px; height: 18px; border-radius: 2px; background: linear-gradient(to bottom, var(--purple), var(--pink)); }\r\n");
      out.write(".btn-submit { display: inline-flex; align-items: center; gap: 8px; padding: 10px 22px; border-radius: 10px; background: linear-gradient(135deg, var(--purple), var(--pink)); color: white; text-decoration: none; font-family: 'Rajdhani'; font-size: 0.9rem; font-weight: 700; border: none; cursor: pointer; transition: all 0.3s; box-shadow: 0 4px 20px rgba(139,92,246,0.3); }\r\n");
      out.write(".btn-submit:hover { transform: translateY(-2px); box-shadow: 0 8px 30px rgba(139,92,246,0.5); }\r\n");
      out.write("\r\n");
      out.write("/* REVIEWS TABLE */\r\n");
      out.write(".review-table-wrap { background: var(--panel); border: 1px solid var(--border); border-radius: 16px; overflow: hidden; }\r\n");
      out.write(".review-table { width: 100%; border-collapse: collapse; }\r\n");
      out.write(".review-table thead tr { background: rgba(139,92,246,0.08); border-bottom: 1px solid var(--border); }\r\n");
      out.write(".review-table th { padding: 14px 20px; text-align: left; font-family: 'Orbitron', sans-serif; font-size: 0.6rem; letter-spacing: 2px; color: var(--dim); text-transform: uppercase; font-weight: 600; }\r\n");
      out.write(".review-table td { padding: 16px 20px; border-bottom: 1px solid rgba(139,92,246,0.06); vertical-align: middle; }\r\n");
      out.write(".review-table tbody tr { transition: background 0.2s; animation: fadeUp 0.4s ease both; }\r\n");
      out.write(".review-table tbody tr:hover { background: rgba(139,92,246,0.05); }\r\n");
      out.write(".review-table tbody tr:last-child td { border-bottom: none; }\r\n");
      out.write("\r\n");
      out.write("/* STARS */\r\n");
      out.write(".stars { display: flex; gap: 3px; }\r\n");
      out.write(".star { font-size: 1rem; }\r\n");
      out.write(".star.filled { color: var(--amber); }\r\n");
      out.write(".star.empty { color: rgba(139,92,246,0.2); }\r\n");
      out.write("\r\n");
      out.write("/* MOD BADGE */\r\n");
      out.write(".mod-badge { display: inline-flex; align-items: center; padding: 4px 10px; border-radius: 6px; background: rgba(139,92,246,0.12); border: 1px solid var(--border); font-family: 'Rajdhani'; font-size: 0.8rem; color: var(--purple-bright); font-weight: 600; }\r\n");
      out.write("\r\n");
      out.write("/* USER CHIP inline */\r\n");
      out.write(".user-inline { display: flex; align-items: center; gap: 8px; }\r\n");
      out.write(".user-dot { width: 28px; height: 28px; border-radius: 50%; background: linear-gradient(135deg, var(--purple), var(--pink)); display: flex; align-items: center; justify-content: center; font-size: 0.7rem; font-weight: 700; font-family: 'Orbitron'; flex-shrink: 0; }\r\n");
      out.write(".user-inline span { font-family: 'Rajdhani'; font-size: 0.9rem; color: var(--white); font-weight: 600; }\r\n");
      out.write("\r\n");
      out.write("/* COMMENT */\r\n");
      out.write(".comment-text { font-size: 0.85rem; color: var(--dim); max-width: 300px; line-height: 1.5; }\r\n");
      out.write("\r\n");
      out.write("/* ACTIONS */\r\n");
      out.write(".actions { display: flex; gap: 8px; }\r\n");
      out.write(".btn-card { padding: 7px 14px; border-radius: 8px; font-family: 'Rajdhani'; font-size: 0.8rem; font-weight: 700; cursor: pointer; transition: all 0.25s; border: 1px solid; text-align: center; text-decoration: none; display: inline-flex; align-items: center; gap: 5px; }\r\n");
      out.write(".btn-edit { background: transparent; border-color: rgba(59,130,246,0.4); color: var(--blue-bright); }\r\n");
      out.write(".btn-edit:hover { background: rgba(59,130,246,0.12); border-color: var(--blue); }\r\n");
      out.write(".btn-del-form button { background: transparent; border: 1px solid rgba(236,72,153,0.35); border-radius: 8px; color: var(--pink); padding: 7px 14px; font-family: 'Rajdhani'; font-size: 0.8rem; font-weight: 700; cursor: pointer; transition: all 0.25s; display: inline-flex; align-items: center; gap: 5px; }\r\n");
      out.write(".btn-del-form button:hover { background: rgba(236,72,153,0.1); border-color: var(--pink); }\r\n");
      out.write("\r\n");
      out.write("/* DATE */\r\n");
      out.write(".date-text { font-size: 0.75rem; color: var(--dim); font-family: 'Rajdhani'; }\r\n");
      out.write("\r\n");
      out.write("/* EMPTY */\r\n");
      out.write(".empty-state { text-align: center; padding: 80px 20px; color: var(--dim); }\r\n");
      out.write(".empty-state .ei { font-size: 4rem; margin-bottom: 16px; }\r\n");
      out.write(".empty-state p { font-family: 'Rajdhani'; font-size: 1.1rem; }\r\n");
      out.write("\r\n");
      out.write("::-webkit-scrollbar { width: 5px; }\r\n");
      out.write("::-webkit-scrollbar-track { background: var(--bg); }\r\n");
      out.write("::-webkit-scrollbar-thumb { background: linear-gradient(var(--purple), var(--pink)); border-radius: 99px; }\r\n");
      out.write("@keyframes fadeUp { from { opacity: 0; transform: translateY(12px); } to { opacity: 1; transform: translateY(0); } }\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<div class=\"blob blob-1\"></div>\r\n");
      out.write("<div class=\"blob blob-2\"></div>\r\n");
      out.write("<div class=\"blob blob-3\"></div>\r\n");
      out.write("\r\n");
      out.write("<aside class=\"sidebar\">\r\n");
      out.write("    <div class=\"logo\">⚡ GAMEVERSE ACADEMY</div>\r\n");
      out.write("    <div class=\"logo-divider\"></div>\r\n");
      out.write("    <nav class=\"nav-section\">\r\n");
      out.write("        <span class=\"nav-label\">Navigation</span>\r\n");
      out.write("        <a href=\"mods\" class=\"nav-item\">🏠 Dashboard</a>\r\n");
      out.write("        <a href=\"ModSubmitController\" class=\"nav-item\">➕ Submit a Mod</a>\r\n");
      out.write("        <a href=\"reviews\" class=\"nav-item active\">⭐ Reviews</a>\r\n");
      out.write("    </nav>\r\n");
      out.write("    <nav class=\"nav-section\">\r\n");
      out.write("        <span class=\"nav-label\">Categories</span>\r\n");
      out.write("        <a href=\"mods?category=Graphique\" class=\"nav-item\">🎨 Graphics</a>\r\n");
      out.write("        <a href=\"mods?category=Gameplay\" class=\"nav-item\">🕹️ Gameplay</a>\r\n");
      out.write("        <a href=\"mods?category=Map\" class=\"nav-item\">🗺️ Maps</a>\r\n");
      out.write("        <a href=\"mods?category=Script\" class=\"nav-item\">📜 Scripts</a>\r\n");
      out.write("    </nav>\r\n");
      out.write("    <div class=\"sidebar-footer\">\r\n");
      out.write("        <a href=\"index.html\" class=\"nav-item\">🚪 Logout</a>\r\n");
      out.write("        <div class=\"user-chip\">\r\n");
      out.write("            <div class=\"user-avatar\">");
      out.print( userLogin != null ? userLogin.substring(0,1).toUpperCase() : "G" );
      out.write("</div>\r\n");
      out.write("            <div>\r\n");
      out.write("                <div class=\"user-name\">");
      out.print( userLogin != null ? userLogin : "Guest" );
      out.write("</div>\r\n");
      out.write("                <div class=\"user-role\">Mod Creator</div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</aside>\r\n");
      out.write("\r\n");
      out.write("<main class=\"main\">\r\n");
      out.write("    <div class=\"top-bar\">\r\n");
      out.write("        <div class=\"page-title\">⭐ Community Reviews</div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <!-- STATS -->\r\n");
      out.write("    <div class=\"stats-row\">\r\n");
      out.write("        <div class=\"stat-card c1\">\r\n");
      out.write("            <div class=\"stat-icon-wrap\">⭐</div>\r\n");
      out.write("            <div><span class=\"stat-val\">");
      out.print( reviews != null ? reviews.size() : 0 );
      out.write("</span><span class=\"stat-lbl\">Total Reviews</span></div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"stat-card c2\">\r\n");
      out.write("            <div class=\"stat-icon-wrap\">🔥</div>\r\n");
      out.write("            <div><span class=\"stat-val\">Top Rated</span><span class=\"stat-lbl\">Community Picks</span></div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"stat-card c3\">\r\n");
      out.write("            <div class=\"stat-icon-wrap\">💬</div>\r\n");
      out.write("            <div><span class=\"stat-val\">Active</span><span class=\"stat-lbl\">Community Feedback</span></div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <!-- SECTION HEADER -->\r\n");
      out.write("    <div class=\"section-header\">\r\n");
      out.write("        <div class=\"section-title\">All Reviews</div>\r\n");
      out.write("        <a href=\"");
      out.print( request.getContextPath() );
      out.write("/ReviewAddController\" class=\"btn-submit\">➕ Add Review</a>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <!-- TABLE -->\r\n");
      out.write("    <div class=\"review-table-wrap\">\r\n");
      out.write("        ");
 if (reviews != null && !reviews.isEmpty()) { 
      out.write("\r\n");
      out.write("        <table class=\"review-table\">\r\n");
      out.write("            <thead>\r\n");
      out.write("                <tr>\r\n");
      out.write("                    <th>User</th>\r\n");
      out.write("                    <th>Mod</th>\r\n");
      out.write("                    <th>Rating</th>\r\n");
      out.write("                    <th>Comment</th>\r\n");
      out.write("                    <th>Date</th>\r\n");
      out.write("                    <th>Actions</th>\r\n");
      out.write("                </tr>\r\n");
      out.write("            </thead>\r\n");
      out.write("            <tbody>\r\n");
      out.write("            ");
 for (Review r : reviews) { 
      out.write("\r\n");
      out.write("                <tr style=\"animation-delay: ");
      out.print( reviews.indexOf(r) * 0.05 );
      out.write("s\">\r\n");
      out.write("                    <td>\r\n");
      out.write("                        <div class=\"user-inline\">\r\n");
      out.write("                            <div class=\"user-dot\">");
      out.print( r.getUserLogin() != null ? r.getUserLogin().substring(0,1).toUpperCase() : "?" );
      out.write("</div>\r\n");
      out.write("                            <span>");
      out.print( r.getUserLogin() != null ? r.getUserLogin() : "Unknown" );
      out.write("</span>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </td>\r\n");
      out.write("                    <td><span class=\"mod-badge\">🎮 ");
      out.print( r.getModTitle() != null ? r.getModTitle() : "—" );
      out.write("</span></td>\r\n");
      out.write("                    <td>\r\n");
      out.write("                        <div class=\"stars\">\r\n");
      out.write("                            ");
 for (int i = 1; i <= 5; i++) { 
      out.write("\r\n");
      out.write("                                <span class=\"star ");
      out.print( i <= r.getRating() ? "filled" : "empty" );
      out.write("\">★</span>\r\n");
      out.write("                            ");
 } 
      out.write("\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </td>\r\n");
      out.write("                    <td><div class=\"comment-text\">");
      out.print( r.getComment() != null ? r.getComment() : "—" );
      out.write("</div></td>\r\n");
      out.write("                    <td><div class=\"date-text\">");
      out.print( r.getCreatedAt() != null ? r.getCreatedAt().toString().substring(0,10) : "—" );
      out.write("</div></td>\r\n");
      out.write("                    <td>\r\n");
      out.write("                        <div class=\"actions\">\r\n");
      out.write("                            <a href=\"");
      out.print( request.getContextPath() );
      out.write("/ReviewEditController?id=");
      out.print( r.getId() );
      out.write("\" class=\"btn-card btn-edit\">✏️ Edit</a>\r\n");
      out.write("                            <form action=\"");
      out.print( request.getContextPath() );
      out.write("/ReviewDeleteController\" method=\"post\" class=\"btn-del-form\">\r\n");
      out.write("                                <input type=\"hidden\" name=\"id\" value=\"");
      out.print( r.getId() );
      out.write("\">\r\n");
      out.write("                                <button type=\"submit\" onclick=\"return confirm('Delete this review?')\">🗑 Delete</button>\r\n");
      out.write("                            </form>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </td>\r\n");
      out.write("                </tr>\r\n");
      out.write("            ");
 } 
      out.write("\r\n");
      out.write("            </tbody>\r\n");
      out.write("        </table>\r\n");
      out.write("        ");
 } else { 
      out.write("\r\n");
      out.write("        <div class=\"empty-state\">\r\n");
      out.write("            <div class=\"ei\">⭐</div>\r\n");
      out.write("            <p>No reviews yet. Be the first to review a mod!</p>\r\n");
      out.write("        </div>\r\n");
      out.write("        ");
 } 
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("</main>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
