/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.18
 * Generated at: 2026-03-25 10:43:46 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class submitMod_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <title>Soumettre un mod — GameVerse Academy</title>\r\n");
      out.write("    <style>\r\n");
      out.write("        body { font-family: Arial, sans-serif; background: #0D1B2A; color: #CDD6F4; }\r\n");
      out.write("        .container { max-width: 600px; margin: 60px auto; background: #1E3A5F;\r\n");
      out.write("                     padding: 32px; border-radius: 10px; }\r\n");
      out.write("        h1   { color: #4A90D9; margin-bottom: 24px; }\r\n");
      out.write("        label { display: block; margin-top: 16px; font-weight: bold; }\r\n");
      out.write("        input, select, textarea {\r\n");
      out.write("            width: 100%; padding: 10px; margin-top: 6px;\r\n");
      out.write("            background: #0D1B2A; color: #CDD6F4;\r\n");
      out.write("            border: 1px solid #4A90D9; border-radius: 6px; box-sizing: border-box; }\r\n");
      out.write("        textarea { height: 120px; resize: vertical; }\r\n");
      out.write("        button   { margin-top: 24px; padding: 12px 28px; background: #4A90D9;\r\n");
      out.write("                   color: white; border: none; border-radius: 6px;\r\n");
      out.write("                   cursor: pointer; font-size: 15px; }\r\n");
      out.write("        .success { background: #1B5E20; padding: 12px;\r\n");
      out.write("                   border-radius: 6px; margin-bottom: 16px; }\r\n");
      out.write("        .error   { background: #B71C1C; padding: 12px;\r\n");
      out.write("                   border-radius: 6px; margin-bottom: 16px; }\r\n");
      out.write("    </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<div class=\"container\">\r\n");
      out.write("    <h1>Soumettre un nouveau mod</h1>\r\n");
      out.write(" \r\n");
      out.write("    ");
      out.write("\r\n");
      out.write("    ");
 String message = (String) request.getAttribute("message"); 
      out.write("\r\n");
      out.write("    ");
 String error   = (String) request.getAttribute("error");   
      out.write("\r\n");
      out.write("    ");
 if (message != null) { 
      out.write("<div class=\"success\">");
      out.print( message );
      out.write("</div>");
 } 
      out.write("\r\n");
      out.write("    ");
 if (error != null)   { 
      out.write("<div class=\"error\">");
      out.print(   error   );
      out.write("</div>");
 } 
      out.write("\r\n");
      out.write(" \r\n");
      out.write("    <form action=\"");
      out.print( request.getContextPath() );
      out.write("/ModSubmitController\" method=\"post\">\r\n");
      out.write(" \r\n");
      out.write("        <label for=\"title\">Titre du mod *</label>\r\n");
      out.write("        <input type=\"text\" id=\"title\" name=\"title\"\r\n");
      out.write("               placeholder=\"Ex: Ultra HD Texture Pack\" required>\r\n");
      out.write(" \r\n");
      out.write("        <label for=\"category\">Catégorie</label>\r\n");
      out.write("        <select id=\"category\" name=\"category\">\r\n");
      out.write("            <option value=\"Graphique\">Graphique</option>\r\n");
      out.write("            <option value=\"Gameplay\">Gameplay</option>\r\n");
      out.write("            <option value=\"Son\">Son</option>\r\n");
      out.write("            <option value=\"Map\">Map</option>\r\n");
      out.write("            <option value=\"Script\">Script</option>\r\n");
      out.write("            <option value=\"Autre\">Autre</option>\r\n");
      out.write("        </select>\r\n");
      out.write(" \r\n");
      out.write("        <label for=\"author\">Auteur</label>\r\n");
      out.write("        <input type=\"text\" id=\"author\" name=\"author\" placeholder=\"Votre pseudo\">\r\n");
      out.write(" \r\n");
      out.write("        <label for=\"description\">Description</label>\r\n");
      out.write("        <textarea id=\"description\" name=\"description\"\r\n");
      out.write("            placeholder=\"Décrivez votre mod en quelques phrases...\"></textarea>\r\n");
      out.write(" \r\n");
      out.write("        <button type=\"submit\">Soumettre le mod</button>\r\n");
      out.write("    </form>\r\n");
      out.write("</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
